# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QDialog, QFontComboBox, QGroupBox, QHeaderView,
    QKeySequenceEdit, QLabel, QPushButton, QSizePolicy,
    QSlider, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        if not SettingDialog.objectName():
            SettingDialog.setObjectName(u"SettingDialog")
        SettingDialog.resize(520, 360)
        SettingDialog.setSizeGripEnabled(False)
        self.tab_widget = QTabWidget(SettingDialog)
        self.tab_widget.setObjectName(u"tab_widget")
        self.tab_widget.setGeometry(QRect(10, 10, 500, 341))
        self.data = QWidget()
        self.data.setObjectName(u"data")
        self.gb_list = QGroupBox(self.data)
        self.gb_list.setObjectName(u"gb_list")
        self.gb_list.setGeometry(QRect(10, 10, 281, 291))
        self.gb_list.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.gb_list.setFlat(False)
        self.gb_list.setCheckable(False)
        self.list_codes = QTableWidget(self.gb_list)
        self.list_codes.setObjectName(u"list_codes")
        self.list_codes.setGeometry(QRect(10, 20, 200, 261))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_codes.sizePolicy().hasHeightForWidth())
        self.list_codes.setSizePolicy(sizePolicy)
        self.list_codes.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.list_codes.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.list_codes.setShowGrid(True)
        self.list_codes.setRowCount(0)
        self.list_codes.setColumnCount(0)
        self.list_codes.horizontalHeader().setCascadingSectionResizes(True)
        self.list_codes.horizontalHeader().setHighlightSections(True)
        self.list_codes.verticalHeader().setVisible(False)
        self.list_codes.verticalHeader().setCascadingSectionResizes(False)
        self.btn_down = QPushButton(self.gb_list)
        self.btn_down.setObjectName(u"btn_down")
        self.btn_down.setGeometry(QRect(220, 110, 51, 26))
        self.btn_up = QPushButton(self.gb_list)
        self.btn_up.setObjectName(u"btn_up")
        self.btn_up.setGeometry(QRect(220, 80, 51, 26))
        self.btn_del = QPushButton(self.gb_list)
        self.btn_del.setObjectName(u"btn_del")
        self.btn_del.setGeometry(QRect(220, 50, 51, 26))
        self.btn_add = QPushButton(self.gb_list)
        self.btn_add.setObjectName(u"btn_add")
        self.btn_add.setGeometry(QRect(220, 20, 51, 26))
        self.btn_update = QPushButton(self.gb_list)
        self.btn_update.setObjectName(u"btn_update")
        self.btn_update.setGeometry(QRect(220, 250, 51, 26))
        self.gb_data = QGroupBox(self.data)
        self.gb_data.setObjectName(u"gb_data")
        self.gb_data.setGeometry(QRect(300, 10, 190, 291))
        self.slider_interval = QSlider(self.gb_data)
        self.slider_interval.setObjectName(u"slider_interval")
        self.slider_interval.setGeometry(QRect(10, 40, 131, 16))
        self.slider_interval.setMinimum(1)
        self.slider_interval.setMaximum(15)
        self.slider_interval.setPageStep(15)
        self.slider_interval.setSliderPosition(2)
        self.slider_interval.setOrientation(Qt.Orientation.Horizontal)
        self.slider_interval.setInvertedAppearance(False)
        self.slider_interval.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_interval.setTickInterval(1)
        self.label = QLabel(self.gb_data)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 54, 16))
        self.cb_code = QCheckBox(self.gb_data)
        self.cb_code.setObjectName(u"cb_code")
        self.cb_code.setGeometry(QRect(10, 90, 51, 24))
        self.cb_name = QCheckBox(self.gb_data)
        self.cb_name.setObjectName(u"cb_name")
        self.cb_name.setGeometry(QRect(10, 60, 51, 24))
        self.cmb_namelen = QComboBox(self.gb_data)
        self.cmb_namelen.setObjectName(u"cmb_namelen")
        self.cmb_namelen.setGeometry(QRect(70, 60, 89, 26))
        self.cb_type = QCheckBox(self.gb_data)
        self.cb_type.setObjectName(u"cb_type")
        self.cb_type.setGeometry(QRect(70, 90, 88, 24))
        self.cb_price = QCheckBox(self.gb_data)
        self.cb_price.setObjectName(u"cb_price")
        self.cb_price.setGeometry(QRect(10, 120, 51, 24))
        self.cb_diff = QCheckBox(self.gb_data)
        self.cb_diff.setObjectName(u"cb_diff")
        self.cb_diff.setGeometry(QRect(70, 120, 51, 24))
        self.cb_pct = QCheckBox(self.gb_data)
        self.cb_pct.setObjectName(u"cb_pct")
        self.cb_pct.setGeometry(QRect(130, 120, 88, 24))
        self.cb_vol = QCheckBox(self.gb_data)
        self.cb_vol.setObjectName(u"cb_vol")
        self.cb_vol.setGeometry(QRect(10, 180, 51, 24))
        self.cb_amount = QCheckBox(self.gb_data)
        self.cb_amount.setObjectName(u"cb_amount")
        self.cb_amount.setGeometry(QRect(70, 180, 51, 24))
        self.cb_avg = QCheckBox(self.gb_data)
        self.cb_avg.setObjectName(u"cb_avg")
        self.cb_avg.setGeometry(QRect(130, 180, 51, 24))
        self.cb_b1s1 = QCheckBox(self.gb_data)
        self.cb_b1s1.setObjectName(u"cb_b1s1")
        self.cb_b1s1.setGeometry(QRect(70, 150, 88, 24))
        self.cb_commi = QCheckBox(self.gb_data)
        self.cb_commi.setObjectName(u"cb_commi")
        self.cb_commi.setGeometry(QRect(10, 150, 51, 24))
        self.cb_kline = QCheckBox(self.gb_data)
        self.cb_kline.setObjectName(u"cb_kline")
        self.cb_kline.setGeometry(QRect(10, 210, 71, 24))
        self.label_interval = QLabel(self.gb_data)
        self.label_interval.setObjectName(u"label_interval")
        self.label_interval.setGeometry(QRect(150, 40, 31, 16))
        self.tab_widget.addTab(self.data, "")
        self.general = QWidget()
        self.general.setObjectName(u"general")
        self.gb_icon = QGroupBox(self.general)
        self.gb_icon.setObjectName(u"gb_icon")
        self.gb_icon.setGeometry(QRect(310, 10, 171, 61))
        self.cmb_icon = QComboBox(self.gb_icon)
        self.cmb_icon.setObjectName(u"cmb_icon")
        self.cmb_icon.setGeometry(QRect(10, 20, 111, 26))
        self.btn_icon = QPushButton(self.gb_icon)
        self.btn_icon.setObjectName(u"btn_icon")
        self.btn_icon.setGeometry(QRect(130, 20, 31, 26))
        self.gb_key = QGroupBox(self.general)
        self.gb_key.setObjectName(u"gb_key")
        self.gb_key.setGeometry(QRect(310, 80, 171, 161))
        self.gb_key.setCheckable(True)
        self.gb_key.setChecked(False)
        self.label_hide = QLabel(self.gb_key)
        self.label_hide.setObjectName(u"label_hide")
        self.label_hide.setGeometry(QRect(10, 30, 91, 16))
        self.keyseq_hide = QKeySequenceEdit(self.gb_key)
        self.keyseq_hide.setObjectName(u"keyseq_hide")
        self.keyseq_hide.setGeometry(QRect(10, 50, 131, 25))
        self.gb_color = QGroupBox(self.general)
        self.gb_color.setObjectName(u"gb_color")
        self.gb_color.setGeometry(QRect(10, 10, 291, 111))
        self.cb_default_color = QCheckBox(self.gb_color)
        self.cb_default_color.setObjectName(u"cb_default_color")
        self.cb_default_color.setGeometry(QRect(10, 20, 88, 24))
        self.btn_fg_color = QPushButton(self.gb_color)
        self.btn_fg_color.setObjectName(u"btn_fg_color")
        self.btn_fg_color.setGeometry(QRect(100, 20, 81, 26))
        self.btn_bg_color = QPushButton(self.gb_color)
        self.btn_bg_color.setObjectName(u"btn_bg_color")
        self.btn_bg_color.setGeometry(QRect(190, 20, 83, 26))
        self.label_bg = QLabel(self.gb_color)
        self.label_bg.setObjectName(u"label_bg")
        self.label_bg.setGeometry(QRect(10, 50, 91, 16))
        self.label_all = QLabel(self.gb_color)
        self.label_all.setObjectName(u"label_all")
        self.label_all.setGeometry(QRect(10, 80, 91, 16))
        self.slider_bg_alpha = QSlider(self.gb_color)
        self.slider_bg_alpha.setObjectName(u"slider_bg_alpha")
        self.slider_bg_alpha.setGeometry(QRect(100, 50, 131, 16))
        self.slider_bg_alpha.setMinimum(1)
        self.slider_bg_alpha.setMaximum(100)
        self.slider_bg_alpha.setValue(60)
        self.slider_bg_alpha.setOrientation(Qt.Orientation.Horizontal)
        self.slider_all_alpha = QSlider(self.gb_color)
        self.slider_all_alpha.setObjectName(u"slider_all_alpha")
        self.slider_all_alpha.setGeometry(QRect(100, 80, 131, 16))
        self.slider_all_alpha.setMinimum(10)
        self.slider_all_alpha.setMaximum(100)
        self.slider_all_alpha.setValue(80)
        self.slider_all_alpha.setOrientation(Qt.Orientation.Horizontal)
        self.label_bg_alpha = QLabel(self.gb_color)
        self.label_bg_alpha.setObjectName(u"label_bg_alpha")
        self.label_bg_alpha.setGeometry(QRect(240, 50, 31, 16))
        self.label_all_alpha = QLabel(self.gb_color)
        self.label_all_alpha.setObjectName(u"label_all_alpha")
        self.label_all_alpha.setGeometry(QRect(240, 80, 31, 16))
        self.gb_text = QGroupBox(self.general)
        self.gb_text.setObjectName(u"gb_text")
        self.gb_text.setGeometry(QRect(10, 130, 291, 111))
        self.cmb_font = QFontComboBox(self.gb_text)
        self.cmb_font.setObjectName(u"cmb_font")
        self.cmb_font.setGeometry(QRect(100, 20, 171, 25))
        self.label_font = QLabel(self.gb_text)
        self.label_font.setObjectName(u"label_font")
        self.label_font.setGeometry(QRect(10, 20, 41, 25))
        self.label_font_size = QLabel(self.gb_text)
        self.label_font_size.setObjectName(u"label_font_size")
        self.label_font_size.setGeometry(QRect(10, 50, 41, 16))
        self.label_line_interval = QLabel(self.gb_text)
        self.label_line_interval.setObjectName(u"label_line_interval")
        self.label_line_interval.setGeometry(QRect(10, 80, 41, 16))
        self.slider_font_size = QSlider(self.gb_text)
        self.slider_font_size.setObjectName(u"slider_font_size")
        self.slider_font_size.setGeometry(QRect(100, 50, 131, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.slider_font_size.sizePolicy().hasHeightForWidth())
        self.slider_font_size.setSizePolicy(sizePolicy1)
        self.slider_font_size.setMinimum(5)
        self.slider_font_size.setMaximum(15)
        self.slider_font_size.setValue(10)
        self.slider_font_size.setOrientation(Qt.Orientation.Horizontal)
        self.slider_line_interval = QSlider(self.gb_text)
        self.slider_line_interval.setObjectName(u"slider_line_interval")
        self.slider_line_interval.setGeometry(QRect(100, 80, 131, 20))
        self.slider_line_interval.setMaximum(20)
        self.slider_line_interval.setValue(3)
        self.slider_line_interval.setOrientation(Qt.Orientation.Horizontal)
        self.label_current_font_size = QLabel(self.gb_text)
        self.label_current_font_size.setObjectName(u"label_current_font_size")
        self.label_current_font_size.setGeometry(QRect(240, 50, 41, 16))
        self.label_current_line_interval = QLabel(self.gb_text)
        self.label_current_line_interval.setObjectName(u"label_current_line_interval")
        self.label_current_line_interval.setGeometry(QRect(240, 80, 41, 16))
        self.gb_fcn = QGroupBox(self.general)
        self.gb_fcn.setObjectName(u"gb_fcn")
        self.gb_fcn.setGeometry(QRect(180, 250, 121, 51))
        self.cb_auto_start = QCheckBox(self.gb_fcn)
        self.cb_auto_start.setObjectName(u"cb_auto_start")
        self.cb_auto_start.setGeometry(QRect(10, 20, 88, 24))
        self.gb_tabel = QGroupBox(self.general)
        self.gb_tabel.setObjectName(u"gb_tabel")
        self.gb_tabel.setGeometry(QRect(10, 250, 161, 51))
        self.cb_head = QCheckBox(self.gb_tabel)
        self.cb_head.setObjectName(u"cb_head")
        self.cb_head.setGeometry(QRect(10, 20, 61, 24))
        self.cb_grid = QCheckBox(self.gb_tabel)
        self.cb_grid.setObjectName(u"cb_grid")
        self.cb_grid.setGeometry(QRect(80, 20, 51, 24))
        self.label_info = QLabel(self.general)
        self.label_info.setObjectName(u"label_info")
        self.label_info.setGeometry(QRect(310, 260, 171, 41))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_info.setFont(font)
        self.label_info.setTextFormat(Qt.TextFormat.RichText)
        self.label_info.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_info.setOpenExternalLinks(True)
        self.tab_widget.addTab(self.general, "")

        self.retranslateUi(SettingDialog)

        self.tab_widget.setCurrentIndex(1)
        self.cmb_icon.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(SettingDialog)
    # setupUi

    def retranslateUi(self, SettingDialog):
        SettingDialog.setWindowTitle(QCoreApplication.translate("SettingDialog", u"\u8bbe\u7f6e", None))
        self.gb_list.setTitle(QCoreApplication.translate("SettingDialog", u"\u81ea\u9009\u5217\u8868", None))
        self.btn_down.setText(QCoreApplication.translate("SettingDialog", u"\u4e0b\u79fb", None))
        self.btn_up.setText(QCoreApplication.translate("SettingDialog", u"\u4e0a\u79fb", None))
        self.btn_del.setText(QCoreApplication.translate("SettingDialog", u"\u5220\u9664", None))
        self.btn_add.setText(QCoreApplication.translate("SettingDialog", u"\u6dfb\u52a0", None))
        self.btn_update.setText(QCoreApplication.translate("SettingDialog", u"\u66f4\u65b0", None))
        self.gb_data.setTitle(QCoreApplication.translate("SettingDialog", u"\u663e\u793a\u6570\u636e", None))
        self.label.setText(QCoreApplication.translate("SettingDialog", u"\u5237\u65b0\u95f4\u9694\uff1a", None))
        self.cb_code.setText(QCoreApplication.translate("SettingDialog", u"\u4ee3\u7801", None))
        self.cb_name.setText(QCoreApplication.translate("SettingDialog", u"\u540d\u79f0", None))
        self.cb_type.setText(QCoreApplication.translate("SettingDialog", u"\u7c7b\u578b", None))
        self.cb_price.setText(QCoreApplication.translate("SettingDialog", u"\u73b0\u4ef7", None))
        self.cb_diff.setText(QCoreApplication.translate("SettingDialog", u"\u6da8\u8dcc", None))
        self.cb_pct.setText(QCoreApplication.translate("SettingDialog", u"\u6da8\u5e45", None))
        self.cb_vol.setText(QCoreApplication.translate("SettingDialog", u"\u91cf", None))
        self.cb_amount.setText(QCoreApplication.translate("SettingDialog", u"\u989d", None))
        self.cb_avg.setText(QCoreApplication.translate("SettingDialog", u"\u5747\u4ef7", None))
        self.cb_b1s1.setText(QCoreApplication.translate("SettingDialog", u"\u4e70\u4e00/\u5356\u4e00", None))
        self.cb_commi.setText(QCoreApplication.translate("SettingDialog", u"\u59d4\u6bd4", None))
        self.cb_kline.setText(QCoreApplication.translate("SettingDialog", u"\u65e5K\u7ebf", None))
        self.label_interval.setText(QCoreApplication.translate("SettingDialog", u"2s", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.data), QCoreApplication.translate("SettingDialog", u"\u6570\u636e", None))
        self.gb_icon.setTitle(QCoreApplication.translate("SettingDialog", u"\u4efb\u52a1\u680f\u56fe\u6807", None))
        self.btn_icon.setText(QCoreApplication.translate("SettingDialog", u"...", None))
        self.gb_key.setTitle(QCoreApplication.translate("SettingDialog", u"\u5feb\u6377\u952e", None))
        self.label_hide.setText(QCoreApplication.translate("SettingDialog", u"\u663e\u793a/\u9690\u85cf\u6d6e\u7a97\uff1a", None))
        self.gb_color.setTitle(QCoreApplication.translate("SettingDialog", u"\u989c\u8272\u4e0e\u900f\u660e\u5ea6", None))
        self.cb_default_color.setText(QCoreApplication.translate("SettingDialog", u"\u9ed8\u8ba4\u989c\u8272", None))
        self.btn_fg_color.setText(QCoreApplication.translate("SettingDialog", u"\u6587\u5b57\u989c\u8272...", None))
        self.btn_bg_color.setText(QCoreApplication.translate("SettingDialog", u"\u80cc\u666f\u989c\u8272...", None))
        self.label_bg.setText(QCoreApplication.translate("SettingDialog", u"\u80cc\u666f\u4e0d\u900f\u660e\u5ea6\uff1a", None))
        self.label_all.setText(QCoreApplication.translate("SettingDialog", u"\u6574\u4f53\u4e0d\u900f\u660e\u5ea6\uff1a", None))
        self.label_bg_alpha.setText(QCoreApplication.translate("SettingDialog", u"100%", None))
        self.label_all_alpha.setText(QCoreApplication.translate("SettingDialog", u"100%", None))
        self.gb_text.setTitle(QCoreApplication.translate("SettingDialog", u"\u5b57\u4f53\u4e0e\u884c\u8ddd", None))
        self.label_font.setText(QCoreApplication.translate("SettingDialog", u"\u5b57\u4f53\uff1a", None))
        self.label_font_size.setText(QCoreApplication.translate("SettingDialog", u"\u5927\u5c0f\uff1a", None))
        self.label_line_interval.setText(QCoreApplication.translate("SettingDialog", u"\u884c\u8ddd\uff1a", None))
        self.label_current_font_size.setText(QCoreApplication.translate("SettingDialog", u"00 pt", None))
        self.label_current_line_interval.setText(QCoreApplication.translate("SettingDialog", u"+0 px", None))
        self.gb_fcn.setTitle(QCoreApplication.translate("SettingDialog", u"\u529f\u80fd", None))
        self.cb_auto_start.setText(QCoreApplication.translate("SettingDialog", u"\u5f00\u673a\u542f\u52a8", None))
        self.gb_tabel.setTitle(QCoreApplication.translate("SettingDialog", u"\u8868\u683c\u5916\u89c2", None))
        self.cb_head.setText(QCoreApplication.translate("SettingDialog", u"\u8868\u5934", None))
        self.cb_grid.setText(QCoreApplication.translate("SettingDialog", u"\u7f51\u683c", None))
        self.label_info.setText(QCoreApplication.translate("SettingDialog", u"StockWidget v1.4.0", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general), QCoreApplication.translate("SettingDialog", u"\u901a\u7528", None))
    # retranslateUi

